# Spring Boot Application Properties
spring.application.name=TIFF MANAGER

# SQLite Database Configuration
spring.datasource.url=jdbc:sqlite:./tiff_manager.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging Configuration
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.example.tiffmanager=INFO

# Disable Spring Boot Web Server
spring.main.web-application-type=none
